version: '3.5'

services:
  ui-simplilearn:
    build:
      context: ./simplilearn-ui
      dockerfile: Dockerfile
    # stdin_open: true
    # volumes:
    #   - ./simplilearn-ui/src:/app/src:delegated
    #   - ./simplilearn-ui/public:/app/public:delegated
    depends_on:
      - api-simplilearn
    ports:
      - 3000:3000
    networks:
      - s-api-ui
    logging:
      options:
        max-size: 10m

  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports: 
      - "80:80"
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf


  api-simplilearn:
    build:
      context: ./simplilearn-api
      dockerfile: Dockerfile
    command: ['npm', 'start']
    restart: on-failure
    environment:
      MONGO_URL: 'mongodb://mongo-simplilearn/simplileardb'
    volumes:
      - ./simplilearn-api/build:/simplilearn-api/build:delegated
      - ./simplilearn-api/package.json:/simplilearn-api/package.json:delegated
    depends_on:
      - api-watch-simplilearn
      - mongo-simplilearn
    ports:
      - 8000:8000
    networks:
      - s-api-ui

  api-watch-simplilearn:
    build:
      context: ./simplilearn-api
      dockerfile: Dockerfile
    command: ['npm', 'run', 'watch']
    networks:
      - s-api-ui
    volumes:
      - ./simplilearn-api/src:/simplilearn-api/src:delegated
      - ./simplilearn-api/build:/simplilearn-api/build:delegated
      - ./simplilearn-api/.babelrc:/simplilearn-api/.babelrc:delegated
    logging:
      options:
        max-size: 10m

  mongo-simplilearn:
    image: mongo:latest
    container_name: mongo-sim
    volumes:
      - mongo-simplilearn:/data/db
    logging:
      options:
        max-size: 10m
    networks:
      - s-api-ui
    ports:
      - 27017:27017

volumes:
  mongo-simplilearn:
  chaindata:

networks:
 s-api-ui:
